# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: gitpod/workspace-postgres
# Command to start on workspace startup (optional)
tasks:
  - init: >
        python3 -m pip install -r requirements.txt && python3 manage.py migrate
    command: >
        python3 manage.py runserver 0.0.0.0:8080
# Ports to expose on workspace startup (optional)
ports:
  - port: 8080
    onOpen: open-preview
