# Generated by Django 3.1 on 2020-08-27 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm_Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('positioning', models.CharField(choices=[('S', 'Small'), ('M', 'Mid'), ('L', 'Large')], default='S', max_length=10)),
                ('position', models.CharField(choices=[('S', 'Short'), ('L', 'Long'), ('PT', 'Pair-Trade')], default='S', max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('outperformance', models.CharField(choices=[('DAX', 'DAX'), ('SEC_EUR', 'Sector Europe'), ('NONE', 'None (for Pair-Trade)')], default='DAX', max_length=30)),
                ('time_horizon', models.CharField(choices=[('1w', '1 Week'), ('2w', '2 Weeks'), ('1m', '1 Month'), ('3m', '3 Month'), ('6m', '6 Month'), ('1y', '1 Year')], default='1w', max_length=10)),
                ('bloomberg_ticker_1', models.CharField(max_length=50)),
                ('bloomberg_ticker_2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['starting_date'],
            },
        ),
    ]
